---
title: "Cis SuShiE Fine-Mapping"
author: "Claudia Krueger"
date: "2025-07-01"
output: html_document
---

**Create Cis Window File for Input**
```{r}
library(dplyr)
library(data.table)

#read in full file location
positions <- fread("~/protein_locations/allchr_protein_location_file", header=TRUE)

#edit start and end
windows <- positions %>%
  summarise(
    OlinkID,
    chr = gsub("chr", "", chr),
    left = positions$left - 1000000,
    right = positions$right + 1000000,
    .groups = 'drop'
  )

#save
write.table(windows, "~/sushie/cis_windows.txt", col.names=TRUE, row.names=FALSE, sep="\t", quote=FALSE)
```

**Format Phenotype File for Input (~/sushie/pheno_format.R)**
```{r}
#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(dplyr)
  library(data.table)
})

#arguments
args <- commandArgs(trailingOnly = TRUE)
protein <- args[1]
pops <- c("euro_amer", "afr_amer", "chn_amer", "hisp_amer") #ancestry specific folder

for (pop in pops) {
  lm_file <- paste0("~/", pop, "/tensor_lm_table.bed")
  lm_table <- fread(lm_file)
  column_names <- colnames(lm_table)
  sample_ids <- column_names[5:length(column_names)]
  no_loc_table <- lm_table %>% select(4:ncol(.))
  transposed_table <- t(no_loc_table)
  colnames(transposed_table) <- transposed_table[1, ]
  transposed_table <- transposed_table[-1, ]
  combo_table <- cbind(sample_ids, transposed_table)
  combo_table <- as.data.frame(combo_table)
  combo_table$sample_ids <- paste(combo_table$sample_ids, combo_table$sample_ids, sep = "_")
  individual_file <- paste0("~/sushie/pheno/", pop, "/", protein, ".pheno")
  individual_protein <- combo_table %>% select(1, all_of(protein))
  write.table(individual_protein, individual_file, col.names = FALSE, row.names = FALSE, sep = "\t", quote = FALSE)
}
```

**Run Cis SuShiE (including Original, META, MEGA, and CV Fusion Formatting)**
```{bash}
#!/bin/bash

#track time
START_TIME=$(date)
echo "Started at: $START_TIME"

NUM_GPUS=2
MAX_JOBS=16

process_protein() {
    local OlinkID="$1"
    local chr="$2"
    local left="$3"
    local right="$4"
    local job_num="$5"
    
    #assign GPU based on job number (alternating)
    local gpu_id=$(( (job_num - 1) % NUM_GPUS ))
    export CUDA_VISIBLE_DEVICES=$gpu_id
    
    echo "[$(date '+%H:%M:%S')] Starting $OlinkID on GPU $gpu_id (Job $job_num)"
    
    #make pheno file
    echo "Making phenotype files for $OlinkID"
    Rscript ~/sushie/pheno_format.R $OlinkID 2>/dev/null

    #make vcf files
    echo "Making VCF files for $OlinkID"
    plink2 --pfile ~/ancestry_specific_folder/euro_amer_final --chr "$chr" --from-bp "$left" --to-bp "$right" --export vcf --out ~/sushie/vcf/euro_amer_cis_${OlinkID} --silent
    plink2 --pfile ~/ancestry_specific_folder/afr_amer_final --chr "$chr" --from-bp "$left" --to-bp "$right" --export vcf --out ~/sushie/vcf/afr_amer_cis_${OlinkID} --silent
    plink2 --pfile ~/ancestry_specific_folder/chn_amer_final --chr "$chr" --from-bp "$left" --to-bp "$right" --export vcf --out ~/sushie/vcf/chn_amer_cis_${OlinkID} --silent
    plink2 --pfile ~/ancestry_specific_folder/hisp_amer_final --chr "$chr" --from-bp "$left" --to-bp "$right" --export vcf --out ~/sushie/vcf/hisp_amer_cis_${OlinkID} --silent
    
    #run sushie
    echo "Running SuShiE for $OlinkID"
    if ! sushie finemap --pheno ~/sushie/pheno/euro_amer/${OlinkID}.pheno ~/sushie/pheno/afr_amer/${OlinkID}.pheno ~sushie/pheno/chn_amer/${OlinkID}.pheno ~/sushie/pheno/hisp_amer/${OlinkID}.pheno --vcf ~/sushie/vcf/euro_amer_cis_${OlinkID}.vcf ~/sushie/vcf/afr_amer_cis_${OlinkID}.vcf ~/sushie/vcf/chn_amer_cis_${OlinkID}.vcf ~/sushie/vcf/hisp_amer_cis_${OlinkID}.vcf --trait "$OlinkID" --meta --mega --cv --cv-num 10 --her --seed 123 --output ~/sushie/meta/cis_${OlinkID} 2>&1 | tee /tmp/sushie_${OlinkID}.log; then
        echo "$OlinkID: SuSiE error:" >> ~/sushie/failed_proteins.log
        tail -n 2 /tmp/sushie_${OlinkID}.log >> ~/sushie/failed_proteins.log
        rm /tmp/sushie_${OlinkID}.log
        return 0
    fi
    
    #run fusion format
    echo "Running FUSION format for $OlinkID"
    if ! Rscript ~/R/x86_64-pc-linux-gnu-library/4.4/sushie/misc/make_FUSION.R ~/sushie/meta/cis_${OlinkID}.sushie.weights.tsv ~/sushie/meta/cis_${OlinkID}.sushie.her.tsv ~/sushie/meta/cis_${OlinkID}.sushie.cv.tsv ~/sushie/fusion/cis_${OlinkID} 2>/dev/null; then
        echo "$OlinkID: FUSION failed" >> ~/sushie/failed_proteins.log
        tail -n 2 /tmp/sushie_${OlinkID}.log >> ~/sushie/failed_proteins.log
        rm /tmp/sushie_${OlinkID}.log
        return 0
    fi
    
    echo "[$(date '+%H:%M:%S')] $OlinkID complete"
}

export -f process_protein
export NUM_GPUS

#parallel processing of jobs
tail -n +2 ~/sushie/cis_windows.txt | \
parallel -j $MAX_JOBS --colsep '\t' --env process_protein --line-buffer \
    'process_protein {1} {2} {3} {4} {#}'

#track time
END_TIME=$(date)
echo "Started:  $START_TIME"
echo "Finished: $END_TIME"
echo "Total runtime: $SECONDS seconds"

#track errors
if [ -f ~/sushie/failed_proteins.log ]; then
    FAILED_COUNT=$(wc -l < ~/sushie/failed_proteins.log)
    echo "Failed proteins: $FAILED_COUNT (see ~/sushie/failed_proteins.log)"
else
    echo "All proteins completed successfully!"
fi
```

**Combine meta files, grouping with respective SuShiE method**
```{r}
library(dplyr)
library(stringr)

#root directory
root_dir <- "~/sushie/meta"

#find all condensed finemap files
#meta_files <- list.files(path = root_dir, pattern = "*.sushie.cs.tsv$", recursive = TRUE, full.names = TRUE)
#meta_files <- list.files(path = root_dir, pattern = "*.meta.cs.tsv$", recursive = TRUE, full.names = TRUE)
meta_files <- list.files(path = root_dir, pattern = "*.mega.cs.tsv$", recursive = TRUE, full.names = TRUE)

cat("Found", length(meta_files), "condensed finemap files\n")

#process all files and combine using rbind
all_data <- list()
for (i in 1:length(meta_files)) {
  file <- meta_files[i]
  tryCatch({
    #read the file (only keeping the needed columns)
    data <- read.table(file, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
    
    #keep only the columns we want
    if (all(c("trait", "chrom", "snp", "CSIndex", "alpha") %in% colnames(data))) {
      data <- data[, c("trait", "chrom", "snp", "CSIndex", "alpha")]
      
      #check if first row has actual data (not empty/NA)
      if (nrow(data) > 0 && !is.na(data$snp[1]) && data$snp[1] != "") {
        all_data[[i]] <- data
        cat("Added data from:", file, "\n")
      } else {
        cat("Skipping file with no credible sets:", file, "\n")
      }
    } else {
      cat("File missing required columns, skipping:", file, "\n")
    }
  }, error = function(e) {
    cat("ERROR processing file:", file, ":", e$message, "\n")
  })
}

#combine all successful results
combined_results <- do.call(rbind, all_data)

#rename columns
colnames(combined_results) <- c("sushie_phenotype_id", "sushie_chr", "sushie_variant_id", "sushie_cs_label", "sushie_pip")

#count unique phenotype_id and cs_label pairs
gene_cs_pairs <- combined_results %>%
  select(sushie_phenotype_id, sushie_cs_label) %>%
  distinct()
num_unique_pairs <- nrow(gene_cs_pairs)

#write the combined results to a file
#combined_file_path <- file.path("~/sushie/sushie_cs/", "meta_cis_sushie_finemap_combined.tsv")
#combined_file_path <- file.path("~/sushie/meta_cs/", "meta_cis_sushie_finemap_combined.tsv")
combined_file_path <- file.path("~/sushie/mega_cs/", "meta_cis_sushie_finemap_combined.tsv")
write.table(combined_results, file = combined_file_path, sep = "\t", row.names = FALSE, quote = FALSE)
```

**Merge SuShiE Meta Files with TensorQTL and SusieR Fine-Mapping Output**
```{r}
library(dplyr)
library(data.table)
library(ggplot2)

sushie <- fread("~/sushie/{sushie/meta/mega}_cs/meta_cis_sushie_finemap_combined.tsv", header = TRUE)
susie <- fread("~/all_race_ancestry_folder/0.05cis_R_vs_tensor.tsv", header = TRUE)

sushie_table <- full_join(susie, sushie, by=c("phenotype_id"="sushie_phenotype_id", "SNP"="sushie_variant_id"))
final_sushie_table <- sushie_table %>% select(phenotype_id, SNP, tensor_CS, susieR_CS, sushie_cs_label, tensor_PIP, susieR_PIP, sushie_pip)
colnames(final_sushie_table) <- c("phenotype_id", "SNP", "tensor_CS", "susieR_CS", "sushie_CS", "tensor_PIP", "susieR_PIP", "sushie_PIP")

write.table(final_sushie_table, "~/sushie/{sushie/meta/mega}_cs/meta_cis_susieR_vs_tensor_vs_sushie.tsv", sep = "\t", row.names = FALSE, quote = FALSE, col.names=TRUE)
```

