---
title: "Colocalization of TOPMed MESA pQTLs and AoU Phenotypes"
author: "Claudia Krueger"
date: "2025-07-31"
output: html_document
---

**Format PWAS Replication File and Upload to AoU**
```{r}
library(data.table)
library(dplyr)

#validated proteins
validated_table <- fread("~/validated_proteins_withsnp.tsv")

#fix phecodes
validated_table_fixed <- validated_table %>%
  mutate(
    aou_code = as.character(aou_code),
    aou_code = case_when(
      aou_code == "CV_401" ~ "CV_401.1",
      aou_code == "EM_202" ~ "EM_202.2",
      aou_code == "GU_582" ~ "GU_582.2",
      aou_code == "NS_333" ~ "NS_333.1",
      TRUE ~ aou_code
    )
  )

#filter
validated_table_filtered <- validated_table_fixed %>% 
  select(gene_name, db_pop, gwas_pop_aou, aou_code, phenotype_name) %>%
  distinct()

#connect gene names to proteins
olink_uniprot <- fread("~/TOPMed/2024-05-03_TOPMed_MESA_Proteomics_Olink/Proteomics_Olink/Mapping_Olink3K_OlinkID_Key_03062024.csv", header=TRUE)
gene_olink <- olink_uniprot %>% select(OlinkID, Assay)
validated_w_olink <- left_join(validated_table_filtered, gene_olink, by=c("gene_name" = "Assay"))

#extract protein locations
protein_locations <- fread("~/qtl_mapping/protein_locations/allchr_protein_location_file", header=TRUE)
validated_w_loc <- left_join(validated_w_olink, protein_locations, by=c("OlinkID"))

#find full cis region
validated_w_region <- validated_w_loc %>%
  mutate(
    left_window = (left - 1000000),
    right_window = (right + 1000000)
  )

#separate by mesa db population and extract window locations
pops <- c("META", "EUR", "AFR", "AMR")
mesa_cis_windows_list <- list()

for (pop in pops){
  #write filtered file
  validated_mesa <- validated_w_region %>% filter(db_pop == pop)
  file <- paste0("~/mesa_pwas_coloc/validated_info/mesa_", pop, "_olink_ids.txt")
  write.table(validated_mesa, file, row.names = FALSE, sep = "\t", quote = FALSE)
  
  #find unique cis locations
  mesa_cis_windows <- validated_mesa %>% select(OlinkID, chr, left_window, right_window) %>% distinct()
  mesa_cis_windows_list[[pop]] <- mesa_cis_windows
  
}

#extract cis snps from qtl files
for (pop in pops){
  #initialize data frame
  all_cis_pqtls <- data.frame()
  
  #extract olink IDs
  mesa_cis_locations <- mesa_cis_windows_list[[pop]]
  olink_ids <- mesa_cis_locations$OlinkID
  
  #assign population names
  if (pop == "META"){
    mesa_pop <- "all_race"
  } else if (pop == "EUR"){
    mesa_pop <- "euro_amer"
  } else if (pop == "AFR"){
    mesa_pop <- "afr_amer"
  } else if (pop == "AMR"){
    mesa_pop <- "hisp_amer"
  }
  
  #collect all cis-SNPs
  for(id in olink_ids) {
    cat("Processing:", pop, id, "\n")
    row <- mesa_cis_locations %>% filter(OlinkID == id)
    gunzip_cmd <- paste0("gunzip ~/qtl_mapping/", mesa_pop, "/tensorqtl/nominal/nominal", row$chr, "cis_qtls.gz")
    system(gunzip_cmd)
    file_path <- paste0("~/qtl_mapping/", mesa_pop, "/tensorqtl/nominal/nominal", row$chr, "cis_qtls")
    cis_pqtls <- fread(file_path, header=TRUE)
    cis_pqtls_filtered <- cis_pqtls %>% 
      filter(phenotype_id == id) %>%
      mutate(pos = as.integer(sub("^[^:]+:([0-9]+):.*", "\\1", variant_id))) %>%
      filter(pos >= row$left_window & pos <= row$right_window)
    all_cis_pqtls <- rbind(all_cis_pqtls, cis_pqtls_filtered)
    gzip_cmd <- paste0("gzip ~/qtl_mapping/", mesa_pop, "/tensorqtl/nominal/nominal", row$chr, "cis_qtls")
    system(gzip_cmd)
  }
  
  #fix X chromosome labeling
  all_cis_pqtls$variant_id <- gsub("^X", "chrX", all_cis_pqtls$variant_id)
  
  #save per population file
  cis_file <- paste0("~/mesa_pwas_coloc/validated_info/mesa_", pop, "_cis_snps.txt")
  write.table(all_cis_pqtls, cis_file, row.names = FALSE, sep = "\t", quote = FALSE)
  gzip_command <- paste0("gzip ", cis_file)
  system(gzip_command)
  
}

#send pQTL files to all of us
system("gsutil -m cp -v ~/mesa_pwas_coloc/validated_info/mesa_META_cis_snps.txt.gz WORKSPACE_BUCKET")
system("gsutil -m cp -v ~/mesa_pwas_coloc/validated_info/mesa_EUR_cis_snps.txt.gz WORKSPACE_BUCKET")
system("gsutil -m cp -v ~/mesa_pwas_coloc/validated_info/mesa_AFR_cis_snps.txt.gz WORKSPACE_BUCKET")
system("gsutil -m cp -v ~/mesa_pwas_coloc/validated_info/mesa_AMR_cis_snps.txt.gz WORKSPACE_BUCKET")

#make SNP list for all of us
system("cat ~/mesa_pwas_coloc/validated_info/mesa_META_cis_snps.txt | cut -f2 | sort | uniq | awk -F: '{print $0","$1","$2}' > ~/mesa_pwas_coloc/validated_info/mesa_META_snp_list.csv")
system("cat ~/mesa_pwas_coloc/validated_info/mesa_EUR_cis_snps.txt | cut -f2 | sort | uniq | awk -F: '{print $0","$1","$2}' > ~/mesa_pwas_coloc/validated_info/mesa_EUR_snp_list.csv")
system("cat ~/mesa_pwas_coloc/validated_info/mesa_AFR_cis_snps.txt | cut -f2 | sort | uniq | awk -F: '{print $0","$1","$2}' > ~/mesa_pwas_coloc/validated_info/mesa_AFR_snp_list.csv")
system("cat ~/mesa_pwas_coloc/validated_info/mesa_AMR_cis_snps.txt | cut -f2 | sort | uniq | awk -F: '{print $0","$1","$2}' > ~/mesa_pwas_coloc/validated_info/mesa_AMR_snp_list.csv")
system("awk -F',' '!seen[$1]++' ~/mesa_pwas_coloc/validated_info/mesa_META_snp_list.csv ~/mesa_pwas_coloc/validated_info/mesa_EUR_snp_list.csv ~/mesa_pwas_coloc/validated_info/mesa_AFR_snp_list.csv ~/mesa_pwas_coloc/validated_info/mesa_AMR_snp_list.csv > ~/mesa_pwas_coloc/validated_info/mesa_full_snp_list.csv")
system("gzip ~/mesa_pwas_coloc/validated_info/mesa_full_snp_list.csv")
system("gsutil -m cp -v ~/mesa_pwas_coloc/validated_info/mesa_full_snp_list.csv.gz WORKSPACE_BUCKET")

#edit and send list of validated proteins to all of us
final_validated <- validated_table_fixed %>%
  select(db_pop, gwas_pop_aou, aou_code, gene_name) %>%
  distinct()
final_validated_w_olink <- left_join(final_validated, gene_olink, by=c("gene_name" = "Assay"))
final_validated_w_loc <- left_join(final_validated_w_olink, protein_locations, by=c("OlinkID"))
final_validated_w_region <- final_validated_w_loc %>%
  mutate(
    left_window = (left - 1000000),
    right_window = (right + 1000000)
  )
final_validated_w_region$chr <- gsub("chr23", "chrX", final_validated_w_region$chr)
write.table(final_validated_w_region, "~/mesa_pwas_coloc/validated_info/validated_proteins.tsv", row.names = FALSE, sep = "\t", quote = FALSE)

system("gsutil -m cp -v ~/mesa_pwas_coloc/validated_info/validated_proteins.tsv WORKSPACE_BUCKET/validated_proteins.tsv")
```

**Run Hail Wrapper for all phenotpyes to retreive AoU summary statistics**
```{bash}
#!/bin/bash

usage() {
    echo "Usage: $0 --phecode <PHECODE>"
    exit 1
}

#parse command-line arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --phecode)
            PHECODE=$2
            shift 2
            ;;
        *)
            echo "unknown flag: $1"
            usage
            ;;
    esac
done

#check for required argument
if [[ -z "$PHECODE" ]]; then
    usage
fi

#define populations
POPS=("META" "EUR" "AFR" "AMR")

chmod +x ~/mesa_coloc/00hail_wrapper.sh

#run in parallel
for POP in "${POPS[@]}"; do
    (
        echo "Starting analysis for phecode $PHECODE, population $POP..."
        /home/jupyter/mesa_pwas/00hail_wrapper.sh --phecode "$PHECODE" --pop "$POP"
        echo "Completed phecode $PHECODE, population $POP"
    ) > ~/00${POP}_${PHECODE}_hail.log 2>&1 &
done

#wait for all background jobs to complete
wait

echo "All populations completed for phecode $PHECODE"
```

**00hail_wrapper.sh**
```{bash}
#!/bin/bash

#command
usage() {
    echo "Usage: $0 --phecode <PHECODE> --pop <POP>"
    exit 1
}

#command-line arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --phecode)
            PHECODE=$2
            shift 2
            ;;
        --pop)
            POP=$2
            shift 2
            ;;
        *)
            echo "unknown flag: $1"
            usage
            ;;
    esac
done

#check for required arguments
if [[ -z "$PHECODE" || -z "$POP" ]]; then
    usage
fi

#github repo path
REPO=$HOME/mesa_coloc

#download hail table
python "$REPO/01pull_data.py" --phecode "$PHECODE" --pop "$POP"

#format hail tables
Rscript "$REPO/02table_format.R" --phecode "$PHECODE" --pop "$POP"
```

**01pull_data.py**
```{python}
#!/usr/bin/python

#import libraries
try:
    import pandas as pd
except ImportError:
    import subprocess, sys
    subprocess.run([sys.executable, "-m", "pip", "install", "pandas"], check=True)
    import pandas as pd
    
import os
import argparse
import sys
import hail as hl
import subprocess

#arguments
def check_arg(args=None):
    parser = argparse.ArgumentParser(description="import hail table from phenotype accession number")
    parser.add_argument('--phecode', help='path to input file', required='True')
    parser.add_argument('--pop', help='path to input file', required='True')
    return parser.parse_args(args)

args = check_arg(sys.argv[1:])

phenotype_id = args.phecode
pop = args.pop

#check if phecode file exists
path = f"gs://fc-aou-datasets-controlled/AllxAll/v1/ht/ACAF/{pop}/phenotype_{phenotype_id}_ACAF_results.ht"

result = os.system(f"gsutil -u $GOOGLE_PROJECT ls {path} > /dev/null 2>&1")

if result == 0:
    print(f"Phenotype {phenotype_id} is in the All of Us database")
else:
    print(f"Phenotype {phenotype_id} is not in the All of Us database; enter valid phenotype ID")
    sys.exit(1)

#PULL TABLE FROM ALL OF US DATABASE   
#initialize hail
hl.init()

#define bucket to save to
bucket = os.getenv('WORKSPACE_BUCKET')

#find hail table and save to variable
ht = hl.read_table(f"gs://fc-aou-datasets-controlled/AllxAll/v1/ht/ACAF/{pop}/phenotype_{phenotype_id}_ACAF_results.ht")

#columns to keep
desired_columns = ['locus', 'alleles', 'BETA', 'SE', 'Het_Q', 'Pvalue', 'Pvalue_log10', 'CHR', 'POS', 'rank', 'Pvalue_expected', 'Pvalue_expected_log10']

#save the column headers
available_fields = set(ht.row)
key_fields = list(ht.key)
non_key_columns = [col for col in desired_columns if col in available_fields and col not in key_fields]
filtered_ht = ht.select(*non_key_columns)

#add Het_Q column if it doesn't exist
if 'Het_Q' not in available_fields:
    filtered_ht = filtered_ht.annotate(Het_Q=hl.null(hl.tfloat64))

#make sure columns are in the correct order
ordered_columns = [col for col in desired_columns if col in filtered_ht.row]
filtered_ht = filtered_ht.key_by()
ordered_ht = filtered_ht.select(*ordered_columns)

#save full table to bucket for S-PrediXcan input
ht_path = f'{bucket}/data/{pop}_full_{phenotype_id}.tsv'
ordered_ht.export(ht_path)

#CHECK IF FILES ARE SAVED TO BUCKET
try:
    check_filtered = subprocess.check_output(
        f"gsutil ls {bucket}/data/ | grep {ht_path}", 
        shell=True, 
        stderr=subprocess.DEVNULL
    )
    #if command succeeded 
    print("Full file successfully saved to bucket.\n")
except subprocess.CalledProcessError:
    #if command failed
    sys.exit(f"ERROR: File '{ht_path}' was not found in {bucket}/data/.\n")
```

**02table_format.R**
```{r}
#!/usr/bin/R

cat("Beginning table formatting...")

#if needed, install packages
if (!requireNamespace("data.table", quietly = TRUE)) install.packages("data.table")
if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!requireNamespace("tidyr", quietly = TRUE)) install.packages("tidyr")
if (!requireNamespace("argparse", quietly = TRUE)) install.packages("argparse")

#load packages
library(data.table)
library(dplyr)
library(tidyr)
library(argparse)

#set up argparse
parser <- ArgumentParser()
parser$add_argument("--phecode", help="all of us phenotype ID")
parser$add_argument("--pop", help="all of us population ID")

args <- parser$parse_args()

#find bucket
my_bucket <- Sys.getenv('WORKSPACE_BUCKET')

#PERFORM COMMAND LINE FORMATTING FOR S-PREDIXCAN FILE

#unzip files
command2 <- paste0("gsutil cat ", my_bucket, "/data/mesa_full_snp_list", args$pop, ".csv.gz | gunzip > /tmp/mesa_full_snp_list", args$pop, ".txt")
system(command2)

#format reference file
command3 <- paste0(
  "awk -F'[,:]' 'NR>1 {print $1\":\"$2}' /tmp/mesa_full_snp_list", args$pop, ".txt > /tmp/chrpos_allele_table", args$pop, ".tsv")
system(command3)

#make temp files
command4 <- paste0("gsutil cp ", my_bucket, "/data/", args$pop, "_full_", args$phecode,".tsv /tmp/")
system(command4)

#filter SNPs
command5 <- paste0("awk 'NR==FNR{a[$1];next} $1 in a' /tmp/chrpos_allele_table", args$pop, ".tsv /tmp/", args$pop, "_full_", args$phecode, ".tsv > /tmp/mesa_", args$phecode, "_", args$pop, ".tsv")
system(command5)

#save to bucket
command6 <- paste0("gsutil cp /tmp/mesa_", args$phecode, "_", args$pop, ".tsv ", my_bucket, "/data/", args$pop, "_mesa_", args$phecode,".tsv")
system(command6)

#check bucket
check_result2 <- system(paste0("gsutil ls ", my_bucket, "/data/ | grep ", args$pop, "_mesa_", args$phecode, ".tsv"), ignore.stderr = TRUE)

if (check_result2 != 0) {
  stop(paste0("ERROR: File '", args$pop, "_mesa_", args$phecode, ".tsv' was not found in bucket ", my_bucket, "/data/"))
} else {
  cat("Reference mesa file successfully transferred to bucket.\n")
}

#FORMAT TABLES
#read in mesa filtered table
name_of_mesa_file <- paste0(args$pop, "_mesa_", args$phecode, ".tsv")
mesa_command <- paste0("gsutil cp ", my_bucket, "/data/", name_of_mesa_file, " .")

system(mesa_command, intern=TRUE)

mesa_table <- fread(name_of_mesa_file, header=FALSE, sep="\t")
colnames(mesa_table) <- c("locus","alleles","BETA","SE","Het_Q","Pvalue","Pvalue_log10","CHR","POS","rank","Pvalue_expected","Pvalue_expected_log10")

#MESA TABLE
#reformat locus column to chr_pos_ref_alt_b38
mesa_table$locus_formatted <- gsub(":", "_", mesa_table$locus) #colon to underscore
mesa_table$alleles_formatted <- gsub('\\["', "", mesa_table$alleles)  #remove opening [
mesa_table$alleles_formatted <- gsub('"\\]', "", mesa_table$alleles_formatted)  #remove closing ]
mesa_table$alleles_formatted <- gsub('","', "_", mesa_table$alleles_formatted)  #comma to underscore

#split allele column
mesa_table <- mesa_table %>%
  separate(alleles_formatted, into = c("REF", "ALT"), sep = "_", remove=F)

#combine strings
mesa_table$SNP <- paste0(mesa_table$locus_formatted, "_", mesa_table$alleles_formatted, "_b38")
mesa_table$ID <- paste0(mesa_table$locus, ":", mesa_table$REF, ":", mesa_table$ALT)

#remove intermediate columns
mesa_table$locus_formatted <- NULL
mesa_table$alleles_formatted <- NULL

#sort by chr, pos
mesa_table <- mesa_table %>%
  arrange(CHR, POS)

#select columns
final_mesa_table <- mesa_table %>%
  select(locus, alleles, ID, REF, ALT, CHR, POS, BETA, SE, Pvalue, SNP)

#check tables
cat("Final MESA filtered table:\n")
head(final_mesa_table)

#write mesa table
mesa_destination_filename <- paste0(args$pop, "_coloc_mesa_", args$phecode,".tsv")

#store the dataframe in current workspace
write.table(final_mesa_table, mesa_destination_filename, col.names=TRUE, row.names=FALSE, quote=FALSE, sep="\t")

#copy the file from current workspace to the bucket
system(paste0("gsutil cp ./", mesa_destination_filename, " ", my_bucket, "/data/"), intern=TRUE)

#CHECK IF FILES ARE IN THE BUCKET
#mesa file
check_mesa <- system(paste0("gsutil ls ", my_bucket, "/data/ | grep ", mesa_destination_filename), ignore.stderr = TRUE)

if (check_mesa != 0) {
  stop(paste0("ERROR: File '", mesa_destination_filename, "' was not found in bucket ", my_bucket, "/data/"))
} else {
  cat("MESA formatted file successfully saved to bucket.\n")
}

#clean up tmp files
system(paste0("rm -f /tmp/chrpos_allele_table.tsv /tmp/", args$pop, "_full_", args$phecode, ".tsv /tmp/mesa_", args$phecode, ".tsv"), intern=TRUE)
```

**Perform Colocalization Analysis within AoU Researcher Workbench**
```{bash}
#!/usr/bin/env bash
set -euo pipefail

gsutil cp $WORKSPACE_BUCKET/data/validated_proteins.tsv /home/jupyter

#set files
IN="/home/jupyter/validated_proteins.tsv"
SCRIPT="$HOME/mesa_coloc/03coloc.R"
OUT="/home/jupyter/coloc_output.txt"

#initialize output
rm -f "$OUT"

#set column names to index
PHECODE_COLNAME="aou_code"
# MESA phenotype id column (should be something like OIDxxxxx)
OID_COLNAME="OlinkID"
# MESA population id
DBPOP_COLNAME="db_pop"
# AoU population id
GWASPOP_COLNAME="gwas_pop_aou"
# -----------------------------------------------

#find column indices by header name (tab-separated)
get_col() {
  local name="$1"
  awk -v FS='\t' -v colname="$name" '
    NR==1{
      for(i=1;i<=NF;i++){
        if($i==colname){ print i; exit }
      }
      exit 1
    }' "$IN"
}

PHECODE_I=$(get_col "$PHECODE_COLNAME") || { echo "Missing column: $PHECODE_COLNAME"; exit 1; }
OID_I=$(get_col "$OID_COLNAME")         || { echo "Missing column: $OID_COLNAME"; exit 1; }
DBPOP_I=$(get_col "$DBPOP_COLNAME")     || { echo "Missing column: $DBPOP_COLNAME"; exit 1; }
GWASPOP_I=$(get_col "$GWASPOP_COLNAME") || { echo "Missing column: $GWASPOP_COLNAME"; exit 1; }

# echo "Using columns:"
# echo "  phecode  ($PHECODE_COLNAME) -> $PHECODE_I"
# echo "  oid      ($OID_COLNAME)     -> $OID_I"
# echo "  db_pop   ($DBPOP_COLNAME)   -> $DBPOP_I"
# echo "  gwas_pop ($GWASPOP_COLNAME) -> $GWASPOP_I"
# echo

#loop over rows (skip header)
awk -v FS='\t' -v phe_i="$PHECODE_I" -v oid_i="$OID_I" -v db_i="$DBPOP_I" -v gwas_i="$GWASPOP_I" '
  NR>1{
    print $phe_i "\t" $oid_i "\t" $db_i "\t" $gwas_i
  }' "$IN" \
| while IFS=$'\t' read -r phecode OlinkID db_pop gwas_pop; do

    #skip empty lines
    [[ -z "${phecode// }" ]] && continue

    echo "Running: phecode=$phecode oid=$oid db_pop=$db_pop gwas_pop=$gwas_pop"

    Rscript ~/mesa_coloc/03coloc.R \
      --phecode "$phecode" \
      --oid "$OlinkID" \
      --db_pop "$db_pop" \
      --gwas_pop "$gwas_pop" \
      --out "$OUT"

done
```

**03coloc.R**
```{r}
#if needed, install packages
if (!requireNamespace("data.table", quietly = TRUE)) install.packages("data.table")
if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!requireNamespace("coloc", quietly = TRUE)) install.packages("coloc")
if (!requireNamespace("argparse", quietly = TRUE)) install.packages("argparse")

#load packages
library(data.table)
library(dplyr)
library(coloc)
library(argparse)

#set up argparse
parser <- ArgumentParser()
parser$add_argument("--phecode", help="all of us phenotype ID")
parser$add_argument("--oid", help="mesa phenotype ID")
parser$add_argument("--db_pop", help="mesa population ID")
parser$add_argument("--gwas_pop", help="all of us population ID")

args <- parser$parse_args()

#find bucket
my_bucket <- Sys.getenv('WORKSPACE_BUCKET')

#read in MESA pQTL table
name_of_pqtl_file <- paste0("mesa_", args$db_pop, "_cis_snps.txt")
pqtl_command <- paste0("gsutil cp ", my_bucket, "/data/", name_of_pqtl_file, ".gz .")
system(pqtl_command, intern=TRUE)
unzip_command <- paste0("gunzip ", name_of_pqtl_file, ".gz")
system(unzip_command, intern=TRUE)
qtl_data <- fread(name_of_pqtl_file, header=TRUE)
remove_command <- paste0("rm /home/jupyter/", name_of_pqtl_file)
system(remove_command, intern=TRUE)

#read in AoU GWAS table
name_of_gwas_file <- paste0(args$gwas_pop, "_coloc_mesa_", args$phecode, ".tsv")
gwas_command <- paste0("gsutil cp ", my_bucket, "/data/", name_of_gwas_file, " .")
system(gwas_command, intern=TRUE)
gwas_data <- fread(name_of_gwas_file, header=TRUE)

#extract phenotype
phenotype <- args$oid
cat("Processing" , phenotype, "for MESA", db_pop, "+ AoU", gwas_pop, "\n")

#filter QTL data for current phenotype
qtl_subset <- qtl_data[qtl_data$phenotype_id == phenotype, ]

#find common SNPs for each phenotype
common_variants <- intersect(qtl_subset$variant_id, gwas_data$ID)

if (length(common_variants) > 0) {
  #filter to common SNPs
  qtl_coloc <- qtl_subset[qtl_subset$variant_id %in% common_variants, ]
  gwas_coloc <- gwas_data[gwas_data$ID %in% common_variants, ]
  
  #merge tables
  merged_data <- inner_join(gwas_coloc, qtl_coloc, by = c("ID" = "variant_id"))
  head(merged_data)
  
  pre_filter <- (nrow(merged_data))
  
  #remove duplicate SNPs
  duplicate_snps <- merged_data$ID[duplicated(merged_data$ID)]
  if (length(duplicate_snps) > 0) {
    cat("Found", length(duplicate_snps), "duplicate SNPs. Removing duplicates...\n")
    #keep most significant
    merged_data <- merged_data %>%
      group_by(ID) %>%
      slice_min(pval_nominal, n = 1, with_ties = FALSE) %>%
      ungroup()
  }
  
  post_filter <-(nrow(merged_data))
  
  cat("Pre-filter SNP count: ", pre_filter, " Post-filter SNP count: ", post_filter, "\n")
  
  #mesa pop sizes
  if (args$db_pop == "META"){
    mesa_pop_size <- 2953
  } else if (args$db_pop == "EUR"){
    mesa_pop_size <- 1270
  } else if (args$db_pop == "AFR"){
    mesa_pop_size <- 675
  } else if (args$db_pop == "AMR"){
    mesa_pop_size <- 642
  }
  
  #all of us pop sizes
  aou_pop <- args$gwas_pop
  phecode <- args$phecode
  phe_counts <- list(
    BI_164    = list(META = c(case=34238, control=156661),
                     EUR  = c(case=19393, control= 88565),
                     AFR  = c(case= 8322, control= 34053),
                     AMR  = c(case= 5676, control= 27743)),
    CV_401.1  = list(META = c(case=69064, control=124692),
                     EUR  = c(case=41257, control= 68448),
                     AFR  = c(case=16709, control= 25976),
                     AMR  = c(case= 9692, control= 24388)),
    EM_202.2  = list(META = c(case=31368, control=168259),
                     EUR  = c(case=15439, control= 97907),
                     AFR  = c(case= 8475, control= 35468),
                     AMR  = c(case= 6643, control= 28246)),
    EM_239    = list(META = c(case=65107, control=128113),
                     EUR  = c(case=44523, control= 64192),
                     AFR  = c(case=10458, control= 32846),
                     AMR  = c(case= 8446, control= 25580)),
    GU_582.2  = list(META = c(case=13723, control=188331),
                     EUR  = c(case= 8021, control=106189),
                     AFR  = c(case= 3505, control= 41195),
                     AMR  = c(case= 1924, control= 33696)),
    MS_708    = list(META = c(case=40336, control=150312),
                     EUR  = c(case=27618, control= 79091),
                     AFR  = c(case= 7987, control= 34736),
                     AMR  = c(case= 4140, control= 29873)),
    NS_333.1  = list(META = c(case=26263, control=173183),
                     EUR  = c(case=18066, control= 94271),
                     AFR  = c(case= 4765, control= 39718),
                     AMR  = c(case= 2928, control= 32283)),
    RE_475    = list(META = c(case=24791, control=172922),
                     EUR  = c(case=13976, control= 97730),
                     AFR  = c(case= 6049, control= 37697),
                     AMR  = c(case= 4256, control= 30614))
  )
  
  #assign outputs
  cc <- phe_counts[[phecode]][[aou_pop]]
  aou_cases    <- as.integer(cc["case"])
  aou_pop_size <- as.integer(cc["case"] + cc["control"])
  
  #prepare datasets
  dataset1 <- list(
    beta = merged_data$slope,
    varbeta = merged_data$slope_se^2,
    snp = merged_data$ID,
    type = "quant",
    N = mesa_pop_size,
    MAF = merged_data$af
  )
  
  dataset2 <- list(
    beta = merged_data$BETA,
    varbeta = merged_data$SE^2,
    snp = merged_data$ID,
    type = "cc",
    N = aou_pop_size,
    s= aou_cases,
    sdY = 1
  )
  
  #run coloc
  result <- coloc.abf(dataset1, dataset2)
  
  #view summary
  cat("Results for", phenotype, ":\n")
  print(result$summary)
  cat("\n")
  outfile <- "/home/jupyter/coloc_output.txt"
  
  if (nrow(common) > 0) {
    
    result <- coloc.abf(dataset1, dataset2)
    
    row <- data.frame(
      phecode = args$phecode,
      olink_id = args$oid,
      mesa_pop = args$db_pop,
      aou_pop = args$gwas_pop,
      t(result$summary),
      check.names = FALSE
    )
    
    write.table(
      row,
      file = outfile,
      sep = "\t",
      row.names = FALSE,
      col.names = !file.exists(outfile),
      append = TRUE,
      quote = FALSE
    )
    
  } else {
    cat("No common variants found for", phenotype, "\n")
  }
}
```

**Format Colocalization Output**
```{r}
#format final H4 results
table <- fread("~/validated_proteins_withsnp.tsv")
output <- fread("~/mesa_pwas_coloc/aou_formatting/coloc_output.txt")
output_chr23 <- fread("~/mesa_pwas_coloc/aou_formatting/coloc_output_chr23.txt")
output_combined <- rbind(output, output_chr23)

#fix phecodes
table_fixed <- table %>%
  mutate(
    aou_code = as.character(aou_code),
    aou_code = case_when(
      aou_code == "CV_401" ~ "CV_401.1",
      aou_code == "EM_202" ~ "EM_202.2",
      aou_code == "GU_582" ~ "GU_582.2",
      aou_code == "NS_333" ~ "NS_333.1",
      TRUE ~ aou_code
    )
  )

#add OIDs
olink_uniprot <- fread("~/TOPMed/2024-05-03_TOPMed_MESA_Proteomics_Olink/Proteomics_Olink/Mapping_Olink3K_OlinkID_Key_03062024.csv", header=TRUE)
gene_olink <- olink_uniprot %>% select(OlinkID, Assay)
table_w_olink <- left_join(table_fixed, gene_olink, by=c("gene_name" = "Assay"))

#final merge
final_table <- left_join(table_w_olink, output_combined, by=c("aou_code" = "phecode", "OlinkID" = "olink_id", "db_pop" = "mesa_pop", "gwas_pop_aou" = "aou_pop"))
write.table(final_table, "~/mesa_pwas_coloc/final_coloc_output.txt", row.names = FALSE, sep = "\t", quote = FALSE)

#view PP.H4 > 0.8 (coloc: both traits are associated and share the same causal variant)
# 242 combinations
final_table_significant_h4 <- final_table %>% filter(PP.H4.abf >= 0.8)
write.table(final_table_significant_h4, "~/mesa_pwas_coloc/final_coloc_output_significant_H4.txt", row.names = FALSE, sep = "\t", quote = FALSE)

#view PP.H3 > 0.8 (MESA and AoU are associated with the region, but have different causal SNPs)
# 108 combinations
final_table_significant_h3 <- final_table %>% filter(PP.H3.abf >= 0.8)
write.table(final_table_significant_h3, "~/mesa_pwas_coloc/final_coloc_output_significant_H3.txt", row.names = FALSE, sep = "\t", quote = FALSE)

#view PP.H1 > 0.8 (only MESA has a genetic association in the region)
# 27 combinations
final_table_significant_h1 <- final_table %>% filter(PP.H1.abf >= 0.8)
write.table(final_table_significant_h1, "~/mesa_pwas_coloc/final_coloc_output_significant_H1.txt", row.names = FALSE, sep = "\t", quote = FALSE)

#PP.H0 (neither have associations) and PP.H2 (only AoU has an association)
# 0 combinations
final_table_significant_h0 <- final_table %>% filter(PP.H0.abf >= 0.8)
final_table_significant_h2 <- final_table %>% filter(PP.H2.abf >= 0.8)
```

**Find lead SNP for CHRDL1 colocalization visualization**
```{bash}
rsync -avP rsync://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/All_20180418.vcf.gz .
tabix -p vcf All_20180418.vcf.gz
bcftools index -s All_20180418.vcf.gz (view chromosome naming)
bcftools view -r X All_20180418.vcf.gz -Oz -o chr23.vcf.gz
```
```{r}
rsids <- fread("chr23.vcf.gz")

pops <- c("all_race", "euro_amer", "afr_amer", "hisp_amer", "chn_amer")

for (pop in pops){
  nominal <- fread(paste0("~/qtl_mapping/", pop, "/tensorqtl/nominal/nominalchr23cis_qtls.gz"), header = TRUE)
  nominal_filtered <- nominal %>% filter(phenotype_id == "OID20771")
  nominal_filtered$position <- as.numeric(sub("^[^:]+:(\\d+):.*", "\\1", nominal_filtered$variant_id))
  nominal_filtered$log_pval_nominal <- -log10(nominal_filtered$pval_nominal)
  file_path <- paste0("~/mesa_pwas_coloc/OID20771_CHRDL1_EM_239_", pop, "_mesa_coloc_no_ld.txt")
  write.table(nominal_filtered, file_path, col.names=TRUE, row.names=FALSE, quote=FALSE, sep="\t")
}

mesa_meta <- fread("~/mesa_pwas_coloc/OID20771_CHRDL1_EM_239_all_race_mesa_coloc_no_ld.txt")
mesa_eur <- fread("~/mesa_pwas_coloc/OID20771_CHRDL1_EM_239_euro_amer_mesa_coloc_no_ld.txt")
mesa_afr <- fread("~/mesa_pwas_coloc/OID20771_CHRDL1_EM_239_afr_amer_mesa_coloc_no_ld.txt")
mesa_amr <- fread("~/mesa_pwas_coloc/OID20771_CHRDL1_EM_239_hisp_amer_mesa_coloc_no_ld.txt")

mesa_meta_filtered <- mesa_meta %>% 
  select(phenotype_id, variant_id, pval_nominal, log_pval_nominal) %>%
  mutate(
    variant_id = gsub("chr", "", variant_id),
    chr = sub("^([^:]+):.*", "\\1", variant_id),
    position = as.numeric(sub("^[^:]+:(\\d+):.*", "\\1", variant_id))
  ) %>% 
  rename(
    pval_nominal_meta = pval_nominal,
    log_pval_nominal_meta = log_pval_nominal
  )

mesa_eur_filtered <- mesa_eur %>% 
  select(phenotype_id, variant_id, pval_nominal, log_pval_nominal) %>%
  mutate(
    variant_id = gsub("chr", "", variant_id),
    chr = sub("^([^:]+):.*", "\\1", variant_id),
    position = as.numeric(sub("^[^:]+:(\\d+):.*", "\\1", variant_id))
  ) %>% 
  rename(
    pval_nominal_eur = pval_nominal,
    log_pval_nominal_eur = log_pval_nominal
  )

mesa_afr_filtered <- mesa_afr %>% 
  select(phenotype_id, variant_id, pval_nominal, log_pval_nominal) %>%
  mutate(
    variant_id = gsub("chr", "", variant_id),
    chr = sub("^([^:]+):.*", "\\1", variant_id),
    position = as.numeric(sub("^[^:]+:(\\d+):.*", "\\1", variant_id))
  ) %>% 
  rename(
    pval_nominal_afr = pval_nominal,
    log_pval_nominal_afr = log_pval_nominal
  )

mesa_amr_filtered <- mesa_amr %>% 
  select(phenotype_id, variant_id, pval_nominal, log_pval_nominal) %>%
  mutate(
    variant_id = gsub("chr", "", variant_id),
    chr = sub("^([^:]+):.*", "\\1", variant_id),
    position = as.numeric(sub("^[^:]+:(\\d+):.*", "\\1", variant_id))
  ) %>% 
  rename(
    pval_nominal_amr = pval_nominal,
    log_pval_nominal_amr = log_pval_nominal
  )

overlap_mesa <- mesa_meta_filtered %>%
  inner_join(mesa_eur_filtered, by=c("phenotype_id", "variant_id", "chr", "position")) %>%
  inner_join(mesa_afr_filtered, by=c("phenotype_id", "variant_id", "chr", "position")) %>%
  inner_join(mesa_amr_filtered, by=c("phenotype_id", "variant_id", "chr", "position"))

pop_pvals <- c("pval_nominal_eur", "pval_nominal_afr", "pval_nominal_amr")

mesa_overlap_scored <- overlap_mesa %>%
  rowwise() %>%
  mutate(
    # The 'Consistency Score'
    median_pval = median(c_across(all_of(pop_pvals))),
    # The absolute best p-value in any single group (for reference)
    min_pval = min(c_across(all_of(pop_pvals)))
  ) %>%
  ungroup()
mesa_top_consistent_hits <- mesa_overlap_scored %>%
  group_by(phenotype_id) %>%
  #select the row with the lowest median p-value
  slice_min(median_pval, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  #sort by most significant overall
  arrange(median_pval)
mesa_top_consistent_hits$variant_id

aou_meta <- fread("~/mesa_pwas_coloc/aou_formatting/OID20771/META_cis_region_EM_239.tsv")
aou_eur <- fread("~/mesa_pwas_coloc/aou_formatting/OID20771/EUR_cis_region_EM_239.tsv")
aou_afr <- fread("~/mesa_pwas_coloc/aou_formatting/OID20771/AFR_cis_region_EM_239.tsv")
aou_amr <- fread("~/mesa_pwas_coloc/aou_formatting/OID20771/AMR_cis_region_EM_239.tsv")

aou_meta_filtered <- aou_meta %>%
  mutate(
    chr_clean = gsub("chr", "", CHR),
    pos_clean = as.numeric(POS),
    alleles_formatted = gsub('\\["', "", alleles),
    alleles_formatted = gsub('"\\]', "", alleles_formatted),
    alleles_formatted = gsub('","', ":", alleles_formatted),
    full_variant_id = paste(chr_clean, pos_clean, alleles_formatted, sep = ":")
  ) %>% 
  rename(
    variant_id = full_variant_id,
    pval_nominal_meta = Pvalue,
    log_pval_nominal_meta = Pvalue_log10,
    chr = chr_clean,
    position = pos_clean
  ) %>%
  select(variant_id, pval_nominal_meta, log_pval_nominal_meta, chr, position)

aou_eur_filtered <- aou_eur %>%
  mutate(
    chr_clean = gsub("chr", "", CHR),
    pos_clean = as.numeric(POS),
    alleles_formatted = gsub('\\["', "", alleles),
    alleles_formatted = gsub('"\\]', "", alleles_formatted),
    alleles_formatted = gsub('","', ":", alleles_formatted),
    full_variant_id = paste(chr_clean, pos_clean, alleles_formatted, sep = ":")
  ) %>% 
  rename(
    variant_id = full_variant_id,
    pval_nominal_eur = Pvalue,
    log_pval_nominal_eur = Pvalue_log10,
    chr = chr_clean,
    position = pos_clean
  ) %>%
  select(variant_id, pval_nominal_eur, log_pval_nominal_eur, chr, position)

aou_afr_filtered <- aou_afr %>%
  mutate(
    chr_clean = gsub("chr", "", CHR),
    pos_clean = as.numeric(POS),
    alleles_formatted = gsub('\\["', "", alleles),
    alleles_formatted = gsub('"\\]', "", alleles_formatted),
    alleles_formatted = gsub('","', ":", alleles_formatted),
    full_variant_id = paste(chr_clean, pos_clean, alleles_formatted, sep = ":")
  ) %>% 
  rename(
    variant_id = full_variant_id,
    pval_nominal_afr = Pvalue,
    log_pval_nominal_afr = Pvalue_log10,
    chr = chr_clean,
    position = pos_clean
  ) %>%
  select(variant_id, pval_nominal_afr, log_pval_nominal_afr, chr, position)

aou_amr_filtered <- aou_amr %>%
  mutate(
    chr_clean = gsub("chr", "", CHR),
    pos_clean = as.numeric(POS),
    alleles_formatted = gsub('\\["', "", alleles),
    alleles_formatted = gsub('"\\]', "", alleles_formatted),
    alleles_formatted = gsub('","', ":", alleles_formatted),
    full_variant_id = paste(chr_clean, pos_clean, alleles_formatted, sep = ":")
  ) %>% 
  rename(
    variant_id = full_variant_id,
    pval_nominal_amr = Pvalue,
    log_pval_nominal_amr = Pvalue_log10,
    chr = chr_clean,
    position = pos_clean
  ) %>%
  select(variant_id, pval_nominal_amr, log_pval_nominal_amr, chr, position)

overlap_aou <- aou_meta_filtered %>%
  inner_join(aou_eur_filtered, by=c("variant_id", "chr", "position")) %>%
  inner_join(aou_afr_filtered, by=c("variant_id", "chr", "position")) %>%
  inner_join(aou_amr_filtered, by=c("variant_id", "chr", "position"))

aou_overlap_scored <- overlap_aou %>%
  rowwise() %>%
  mutate(
    #the 'Consistency Score'
    median_pval = median(c_across(all_of(pop_pvals))),
    #the absolute best p-value in any single group (for reference)
    min_pval = min(c_across(all_of(pop_pvals)))
  ) %>%
  ungroup()

#mesa v aou
aou_snps_arranged <- aou_overlap_scored %>%
  arrange(median_pval) %>%
  select(variant_id, median_pval, chr, position) %>%
  rename(median_pval_aou = median_pval)
mesa_snps_arranged <- mesa_overlap_scored %>%
  arrange(median_pval) %>%
  select(variant_id, median_pval, chr, position) %>%
  rename(median_pval_mesa = median_pval)

arranged_overlaps <- full_join(aou_snps_arranged, mesa_snps_arranged)

final_overlaps <- arranged_overlaps %>%
  #filter to keep only SNPs present in BOTH studies
  filter(!is.na(median_pval_aou) & !is.na(median_pval_mesa)) %>%
  rowwise() %>%
  mutate(
    #average of the two medians (Global Consistency)
    global_median = median(c(median_pval_aou, median_pval_mesa)),
    #or find the absolute best hit between them
    global_min = min(c(median_pval_aou, median_pval_mesa))
  ) %>%
  ungroup() %>%
  #sort by the best global performance
  arrange(global_median)

top_hit_overall <- final_overlaps %>%
  slice_min(global_median, n = 1)
print(top_hit_overall$variant_id)

find_rsid <- rsids %>%
  filter(`#CHROM` == top_hit_overall$chr, POS == top_hit_overall$position)
print(find_rsid$ID)
```

